/**
 * The 2-of-3 multisig ceremony, run in a real browser and recorded.
 *
 * What this proves, and what it does not. The multisig work is `src/core` only
 * — no popup screens, no `wallet.*` methods, no keyring integration — so there
 * is nothing in the extension UI to click, and this is deliberately not a
 * recording of the wallet. It is a recording of the claim the design rests on:
 * that a Dilithium P2MR PSBT can be parsed, signed, combined and finalized
 * **in a browser with no node**, and that the result is byte-for-byte what
 * btq-core produces.
 *
 * That claim is load-bearing. `docs/MULTISIG.md` §2 shows a node wallet cannot
 * sign one of these inputs from a PSBT at all without prior registration
 * (`FillPSBT`'s fallback is built around `CPubKey`, `src/pubkey.h:39`, and a
 * 1312-byte ML-DSA key cannot exist in that type), so there is no node-side
 * fallback to lean on. Client-side is not the convenient option; it is the only
 * one. This spec is the demonstration that it works.
 *
 * Every fixture comes from `tests/vectors/psbt.json`, generated by driving a
 * real btq-core regtest node — never computed here. The page runs the same
 * `signPsbt` the service worker would call.
 *
 * Recording: `RECORD_VIDEO=1 npx playwright test tests/e2e/multisig.spec.ts`,
 * or `npm run demo:multisig`, which stitches it to demo/btq-multisig.mp4.
 */
import { test, expect, chromium, type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { startCeremony, type Ceremony } from './fixtures/ceremony.js';
import { videoDir } from './fixtures/video.js';
import { installCaptions, scene, dwell } from './fixtures/scene.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const VECTORS = JSON.parse(
  readFileSync(join(HERE, '..', 'vectors', 'psbt.json'), 'utf8'),
) as Vectors;

interface VectorCase {
  name: string;
  m: number;
  n: number;
  keyIndexes: number[];
  signerKeyIndexes: number[];
  address: string;
  unsignedPsbt: string;
  singlySignedPsbts: { keyIndex: number; psbt: string }[];
  combinedPsbt: string;
  finalizedHex: string;
  tamperedPsbt: string;
}
interface Vectors {
  seeds: string[];
  cases: VectorCase[];
}

/** A wider canvas than the popup: this page is a three-party ceremony, not a wallet screen. */
const CANVAS = { width: 1000, height: 720 };

/** Cosigner names, indexed the way the vector indexes keys. */
const NAMES = ['Alice', 'Bob', 'Carol'];

function caseNamed(name: string): VectorCase {
  const found = VECTORS.cases.find((c) => c.name === name);
  if (!found) throw new Error(`psbt.json has no case "${name}"`);
  return found;
}

/** Call into the page's ceremony API and get its structured result back. */
async function act<T>(page: Page, method: string, ...args: unknown[]): Promise<T> {
  return page.evaluate(
    ([m, a]) => {
      const api = (window as unknown as Record<string, Record<string, (...x: unknown[]) => unknown>>)
        .__ceremony;
      if (!api) throw new Error('ceremony page did not install __ceremony');
      const fn = api[m as string];
      if (!fn) throw new Error(`ceremony page has no method "${m as string}"`);
      return fn(...(a as unknown[]));
    },
    [method, args] as [string, unknown[]],
  ) as Promise<T>;
}

test.describe('2-of-3 Dilithium multisig, in the browser', () => {
  let ceremony: Ceremony;

  test.beforeAll(async () => {
    ceremony = await startCeremony();
  });
  test.afterAll(async () => {
    await ceremony?.close();
  });

  test('parses, signs, combines and finalizes — and matches btq-core byte for byte', async () => {
    const v = caseNamed('2-of-3');
    const context = await chromium.launchPersistentContext('', {
      headless: true,
      viewport: CANVAS,
      recordVideo: videoDir(1, 'multisig') ? { dir: videoDir(1, 'multisig')!, size: CANVAS } : undefined,
    });
    await installCaptions(context);
    // Use the context's own first page rather than opening a second. A
    // persistent context starts with a blank page and records it too, and a
    // stray blank clip is what opens a stitched demo on grey.
    const page = context.pages()[0] ?? (await context.newPage());

    try {
      await page.goto(ceremony.url);
      await expect(page.getByTestId('ceremony-log')).toBeVisible();

      // 1 — the cosigner set. Three independent seeds, one key each.
      await scene(page, 1, 'Three wallets, three keys', {
        sub: 'no xpub exists on BTQ, so every key is shared explicitly',
      });
      const seeds = v.keyIndexes.map((i) => VECTORS.seeds[i]!);
      const setup = await act<{ address: string; canonical: string; leafBytes: number }>(
        page, 'setup', seeds, v.m,
      );
      // btq-core built this address from the key list in caller order.
      expect(setup.address).toBe(v.address);
      // And the same keys sorted give a different address — the footgun a wallet
      // must close by canonicalising, documented in docs/MULTISIG.md finding 5.
      expect(setup.canonical).not.toBe(v.address);
      expect(setup.leafBytes).toBe(1319 * v.n + 3);
      await expect(page.getByTestId('ceremony-address')).toHaveText(v.address);
      await dwell(page, 2400);

      // 2 — btq-core's unsigned PSBT, parsed here.
      await scene(page, 2, 'An unsigned PSBT from btq-core', {
        sub: 'built by a real node on regtest; parsed by src/core/psbt',
      });
      const loaded = await act<{ inputs: number }>(page, 'load', v.unsignedPsbt);
      expect(loaded.inputs).toBe(1);
      await dwell(page, 2200);

      // 3 & 4 — two cosigners sign independently, each holding only their own seed.
      const [firstSigner, secondSigner] = v.signerKeyIndexes as [number, number];
      await scene(page, 3, `${NAMES[firstSigner]} signs`, {
        sub: 'ML-DSA-44, 2421 bytes, in this browser',
      });
      const first = await act<{ base64: string; signatures: number }>(page, 'sign', firstSigner);
      expect(first.signatures).toBe(1);
      await dwell(page, 1800);

      await scene(page, 4, `${NAMES[secondSigner]} signs the same PSBT`, {
        sub: 'independently — neither cosigner saw the other',
      });
      await act(
        page, 'load', v.unsignedPsbt,
        `back to the original unsigned PSBT — ${NAMES[secondSigner]} starts from it too`,
      );
      const second = await act<{ base64: string; signatures: number }>(page, 'sign', secondSigner);
      expect(second.signatures).toBe(1);
      await dwell(page, 1800);

      // 5 — combine. This is the operation that makes parallel cosigning work.
      await scene(page, 5, 'Combine', { sub: 'two independent signatures merge into one PSBT' });
      const combined = await act<{ base64: string; signatures: number }>(
        page,
        'combine',
        first.base64,
        second.base64,
      );
      expect(combined.signatures).toBe(v.m);
      await expect(page.getByTestId('ceremony-sigcount')).toContainText(`${v.m}`);
      await dwell(page, 2200);

      // 6 — finalize, then the only assertion that really matters.
      await scene(page, 6, 'Finalize and compare', {
        sub: 'against the transaction btq-core produced from the same PSBT',
      });
      const final = await act<{ hex: string; complete: boolean }>(page, 'finalize');
      expect(final.complete).toBe(true);
      expect(final.hex).toBe(v.finalizedHex);

      const same = await act<boolean>(page, 'verdict', final.hex, v.finalizedHex);
      expect(same).toBe(true);
      await expect(page.getByTestId('ceremony-verdict-head')).toContainText('identical');
      await dwell(page, 3000);

      // 7 — the refusal. A forged signature dies at parse, not at finalize.
      await scene(page, 7, 'A forged signature is refused', {
        sub: 'one byte flipped inside a 2421-byte signature, refused at parse',
      });
      const rejected = await act<boolean>(page, 'reject', v.tamperedPsbt);
      expect(rejected).toBe(true);
      await dwell(page, 2600);
    } finally {
      await page.close();
      await context.close();
    }
  });

  test('the combined PSBT is byte-identical to btq-core combinepsbt', async () => {
    const v = caseNamed('2-of-3');
    const context = await chromium.launchPersistentContext('', {
      headless: true,
      viewport: CANVAS,
    });
    const page = await context.newPage();
    try {
      await page.goto(ceremony.url);
      const seeds = v.keyIndexes.map((i) => VECTORS.seeds[i]!);
      await act(page, 'setup', seeds, v.m);
      const merged = await act<{ base64: string }>(
        page,
        'combine',
        v.singlySignedPsbts[0]!.psbt,
        v.singlySignedPsbts[1]!.psbt,
      );
      // Merging btq-core's own two singly-signed copies must reproduce its
      // combinepsbt output exactly — this is the check that would catch the
      // 0x1B ordering bug a round-trip test cannot see.
      expect(merged.base64).toBe(v.combinedPsbt);
    } finally {
      await page.close();
      await context.close();
    }
  });
});
