#!/usr/bin/env python3
"""Generate tests/vectors/multisig.json from btq-core's own reference code.

None of the output is computed here. The ML-DSA keys come from
test_framework/dilithium.py, which compiles the same pq-crystals sources the
node links; the leaf script comes from feature_p2mr_dilithium_multisig.py's
own threshold_leaf(), the helper whose leaves that functional test spends on a
regtest chain; the merkle root, scriptPubKey and control block come from
test_framework/script.py's p2mr_construct; the address comes from its
segwit_addr encoder. So a green tests/unit/multisig.test.ts means the
TypeScript agrees with btq-core, not with itself.

The seeds are bytes([i + 1]) * 32, the same deterministic keys
feature_p2mr_dilithium_multisig.py uses.

Needs a C compiler (for the Dilithium shared library) and no running node; it
touches nothing outside btq-core's own build cache in $TMPDIR.

    python3 scripts/gen-multisig-vectors.py [--btq-core PATH] [-o PATH]
"""

import argparse
import json
import os
import sys

DEFAULT_BTQ_CORE = [
    os.environ.get("BTQ_CORE_DIR", ""),
    os.path.expanduser("~/Development/btq-core"),
    os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "..", "btq-core")),
]

# btq-core src/kernel/chainparams.cpp:148,267,401,552
HRP = {"mainnet": "qbtc", "testnet": "tbtq", "signet": "qtb", "regtest": "qcrt"}

# (name, m, seed indexes, sort the keys?)
CASES = [
    ("1-of-1", 1, [0], True),
    ("2-of-3", 2, [0, 1, 2], True),
    ("3-of-5", 3, [0, 1, 2, 3, 4], True),
    # Above 16 the threshold has no opcode of its own and becomes a two-byte
    # CScriptNum push, so the leaf is 1319n + 4 rather than 1319n + 3. That is
    # the branch a suite written entirely around 2-of-3 never reaches.
    ("17-of-17", 17, list(range(17)), True),
    # Same keys, same threshold, btq-core's raw caller order. Its address
    # differs from the canonical one whenever seed order is not sorted order —
    # the ordering footgun the wallet closes, pinned as a vector so the
    # TypeScript has to reproduce both leaves.
    ("2-of-3-caller-order", 2, [0, 1, 2], False),
]


def find_btq_core():
    for candidate in DEFAULT_BTQ_CORE:
        if candidate and os.path.isdir(os.path.join(candidate, "test", "functional", "test_framework")):
            return candidate
    return None


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--btq-core", default=None, help="path to a btq-core checkout")
    ap.add_argument("-o", "--out", default=os.path.normpath(
        os.path.join(os.path.dirname(__file__), "..", "tests", "vectors", "multisig.json")))
    args = ap.parse_args()

    core = args.btq_core or find_btq_core()
    if core is None:
        sys.exit("btq-core checkout not found; pass --btq-core PATH or set BTQ_CORE_DIR")
    sys.path.insert(0, os.path.join(core, "test", "functional"))

    from feature_p2mr_dilithium_multisig import threshold_leaf
    from test_framework.dilithium import DilithiumKey, dilithium_available
    from test_framework.script import p2mr_construct
    from test_framework.segwit_addr import encode_segwit_address

    if not dilithium_available():
        sys.exit("btq-core's Dilithium reference library did not build (needs a C compiler)")

    n_seeds = max(max(indexes) for _, _, indexes, _ in CASES) + 1
    seeds = [bytes([i + 1]) * 32 for i in range(n_seeds)]
    keys = [DilithiumKey(seed=s) for s in seeds]

    out = {
        "note": (
            "Generated by scripts/gen-multisig-vectors.py against btq-core's own "
            "reference implementation: test_framework/dilithium.py for the ML-DSA "
            "keys, feature_p2mr_dilithium_multisig.py's threshold_leaf() for the "
            "leaf, test_framework/script.py's p2mr_construct for the tree, "
            "test_framework/segwit_addr.py for the address. Regenerate, never hand-edit."
        ),
        "source": {
            "leafBuilder": "src/script/dilithium_leaf.cpp:13 GetScriptForDilithiumThreshold, "
                           "via test/functional/feature_p2mr_dilithium_multisig.py:55 threshold_leaf",
            "tree": "test/functional/test_framework/script.py p2mr_construct",
            "keys": "DilithiumKey(seed=bytes([i + 1]) * 32), as in feature_p2mr_dilithium_multisig.py",
        },
        "hrp": HRP,
        # Every case names its keys by index into these two lists rather than
        # repeating 2624 hex characters per key per case.
        "seeds": [s.hex() for s in seeds],
        "pubkeys": [k.pubkey.hex() for k in keys],
        "cases": [],
    }

    for name, m, indexes, canonical in CASES:
        order = sorted(indexes, key=lambda i: keys[i].pubkey) if canonical else list(indexes)
        pubkeys = [keys[i].pubkey for i in order]
        leaf = bytes(threshold_leaf(m, pubkeys))
        p2mr = p2mr_construct([("ms", leaf)])
        info = p2mr.leaves["ms"]
        root = p2mr.merkle_root
        assert info.leaf_hash == root, "single-leaf tree: root is the leaf hash"
        assert info.merklebranch == b"", "single-leaf tree: empty merkle branch"
        # 1319 bytes per cosigner, plus OP_0 and OP_GREATERTHANOREQUAL, plus the
        # threshold push: one byte for OP_1..OP_16, two for 17..20.
        assert len(leaf) == 1319 * len(pubkeys) + 2 + (1 if m <= 16 else 2), "unexpected leaf length"
        out["cases"].append({
            "name": name,
            "m": m,
            "n": len(pubkeys),
            "canonicalOrder": canonical,
            # Indexes into "pubkeys", in leaf script order.
            "keyOrder": order,
            "leafScript": leaf.hex(),
            "leafScriptBytes": len(leaf),
            "tapLeafHash": info.leaf_hash.hex(),
            "merkleRoot": root.hex(),
            "scriptPubKey": bytes(p2mr.scriptPubKey).hex(),
            # Leaf version with the parity bit set, then the (empty) merkle branch.
            "controlBlock": (bytes([info.version | 1]) + info.merklebranch).hex(),
            "addresses": {net: encode_segwit_address(hrp, 2, root) for net, hrp in HRP.items()},
        })

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=2)
        fh.write("\n")
    print(f"wrote {args.out} ({len(out['cases'])} cases)")


if __name__ == "__main__":
    main()
