/**
 * Cross-implementation check for the Dilithium threshold leaf.
 *
 * tests/vectors/multisig.json is produced by scripts/gen-multisig-vectors.py,
 * which builds every byte with btq-core's own code: its Dilithium reference
 * library for the keys, its own functional-test threshold_leaf() for the leaf,
 * its p2mr_construct for the tree, its segwit_addr for the address.
 * Reproducing it here is agreement with the node, not with ourselves — the same
 * standard tests/vectors/golden.json holds the single-sig path to. Regenerate
 * the file, never hand-edit it.
 */
import { describe, it, expect } from 'vitest';
import vectors from '../vectors/multisig.json' with { type: 'json' };
import { publicKeyFromSeed, PUBLIC_KEY_BYTES } from '../../src/core/crypto/mldsa.js';
import { commitsToProgram, outputScript, singleKeyLeafScript, tapLeafHash } from '../../src/core/script/p2mr.js';
import type { BtqNetwork } from '../../src/core/script/address.js';
import { HRP, decodeAddress } from '../../src/core/script/address.js';
import {
  LEAF_BYTES_PER_COSIGNER,
  LEAF_SCRIPT_BYTES_FOR,
  MAX_COSIGNERS,
  canonicalCosigners,
  isFullyValidPublicKey,
  multisigAddress,
  multisigControlBlock,
  multisigMerkleRoot,
  multisigOutputScript,
  parseThresholdLeaf,
  thresholdLeafScript,
} from '../../src/core/script/multisig.js';
import { WalletError } from '../../src/core/wallet/errors.js';
import { bytesToHex, hexToBytes } from '../../src/core/util/hex.js';

const NETWORKS = Object.keys(HRP) as BtqNetwork[];

/** The cosigner keys of a case, in the leaf's script order. */
function keysOf(v: { keyOrder: number[] }): Uint8Array[] {
  return v.keyOrder.map((i) => hexToBytes(vectors.pubkeys[i]!));
}

/**
 * A structurally valid 1312-byte blob that is not an ML-DSA key. Neither the
 * leaf builder nor the cosigner check does any lattice arithmetic — they check
 * size and the degenerate encodings — so these are enough to exercise the
 * 20-key ceiling without 21 keygens.
 */
function fixtureKey(seed: number): Uint8Array {
  const k = new Uint8Array(PUBLIC_KEY_BYTES);
  for (let i = 0; i < k.length; i++) k[i] = (seed * 7 + i * 31 + 1) & 0xff;
  return k;
}

describe('multisig vectors (generated by btq-core)', () => {
  it('derives the same ML-DSA public keys btq-core does', () => {
    // If this fails nothing below it means anything: the two implementations
    // would be building leaves out of different keys.
    vectors.seeds.forEach((seedHex, i) => {
      expect(bytesToHex(publicKeyFromSeed(hexToBytes(seedHex)))).toBe(vectors.pubkeys[i]);
    });
  });

  for (const v of vectors.cases) {
    describe(v.name, () => {
      it('reproduces the leaf script byte for byte', () => {
        const leaf = thresholdLeafScript(v.m, keysOf(v));
        expect(bytesToHex(leaf)).toBe(v.leafScript);
        expect(leaf.length).toBe(v.leafScriptBytes);
        // 1319 per cosigner, plus OP_0, OP_GREATERTHANOREQUAL and the threshold
        // push — one byte up to OP_16, two above it.
        expect(leaf.length).toBe(1319 * v.n + 2 + (v.m <= 16 ? 1 : 2));
        expect(leaf.length).toBe(LEAF_SCRIPT_BYTES_FOR(v.n, v.m));
      });

      it('reproduces the tapleaf hash, merkle root and scriptPubKey', () => {
        const leaf = thresholdLeafScript(v.m, keysOf(v));
        expect(bytesToHex(tapLeafHash(leaf))).toBe(v.tapLeafHash);
        // Single-leaf tree: the merkle root is the leaf hash.
        expect(v.merkleRoot).toBe(v.tapLeafHash);
        expect(bytesToHex(outputScript(hexToBytes(v.merkleRoot)))).toBe(v.scriptPubKey);
      });

      it('the leaf and control block commit to the witness program', () => {
        const leaf = thresholdLeafScript(v.m, keysOf(v));
        expect(bytesToHex(multisigControlBlock())).toBe(v.controlBlock);
        expect(commitsToProgram(leaf, multisigControlBlock(), hexToBytes(v.merkleRoot))).toBe(true);
      });

      it('round-trips through parseThresholdLeaf', () => {
        const parsed = parseThresholdLeaf(thresholdLeafScript(v.m, keysOf(v)));
        expect(parsed).not.toBeNull();
        expect(parsed!.m).toBe(v.m);
        expect(parsed!.pubkeys.map(bytesToHex)).toEqual(v.keyOrder.map((i) => vectors.pubkeys[i]));
      });

      if (v.canonicalOrder) {
        it('derives the same address on every network', () => {
          const keys = keysOf(v);
          for (const network of NETWORKS) {
            const address = v.addresses[network as keyof typeof v.addresses];
            expect(multisigAddress(v.m, keys, network)).toBe(address);
            expect(bytesToHex(decodeAddress(address, network).merkleRoot)).toBe(v.merkleRoot);
          }
          expect(v.addresses.testnet.startsWith('tbtq1z')).toBe(true);
          expect(bytesToHex(multisigMerkleRoot(v.m, keys))).toBe(v.merkleRoot);
          expect(bytesToHex(multisigOutputScript(v.m, keys))).toBe(v.scriptPubKey);
        });

        it('derives that address from any enrolment order', () => {
          const keys = keysOf(v);
          const reversed = [...keys].reverse();
          const rotated = [...keys.slice(1), keys[0]!];
          expect(multisigAddress(v.m, reversed, 'testnet')).toBe(v.addresses.testnet);
          expect(multisigAddress(v.m, rotated, 'testnet')).toBe(v.addresses.testnet);
        });
      }
    });
  }

  it('caller key order changes the address, which is why the wallet sorts', () => {
    // btq-core's createdilithiummultisig takes the caller's order unsorted
    // (src/wallet/rpc/dilithium.cpp:500-519). These two cases hold the same
    // three keys and the same threshold and land on different addresses.
    const canonical = vectors.cases.find((c) => c.name === '2-of-3')!;
    const callerOrder = vectors.cases.find((c) => c.name === '2-of-3-caller-order')!;
    expect(new Set(callerOrder.keyOrder)).toEqual(new Set(canonical.keyOrder));
    expect(callerOrder.keyOrder).not.toEqual(canonical.keyOrder);
    expect(callerOrder.addresses.testnet).not.toBe(canonical.addresses.testnet);
    // Ours collapses both orders onto the canonical one.
    expect(multisigAddress(2, keysOf(callerOrder), 'testnet')).toBe(canonical.addresses.testnet);
  });

  it('a 1-of-1 threshold leaf is not a single-key leaf', () => {
    // Worth pinning: they hold the same key and produce different addresses, so
    // a wallet must never treat one as a cheaper spelling of the other.
    const v = vectors.cases.find((c) => c.name === '1-of-1')!;
    const pubkey = keysOf(v)[0]!;
    expect(singleKeyLeafScript(pubkey).length).toBe(1316);
    expect(bytesToHex(thresholdLeafScript(1, [pubkey]))).not.toBe(bytesToHex(singleKeyLeafScript(pubkey)));
    expect(bytesToHex(tapLeafHash(singleKeyLeafScript(pubkey)))).not.toBe(v.merkleRoot);
  });
});

describe('threshold leaf sizing', () => {
  it('is 1319 bytes per cosigner plus 3', () => {
    expect(LEAF_BYTES_PER_COSIGNER).toBe(1319);
    for (let n = 1; n <= MAX_COSIGNERS; n++) expect(LEAF_SCRIPT_BYTES_FOR(n)).toBe(1319 * n + 3);
  });

  it('costs one extra byte for a threshold above 16', () => {
    // OP_1..OP_16 are one byte; 17..20 fall through to a CScriptNum data push.
    // The 17-of-17 vector is the cross-check that those bytes are btq-core's.
    const keys = Array.from({ length: 20 }, (_, i) => fixtureKey(i));
    expect(thresholdLeafScript(16, keys).length).toBe(LEAF_SCRIPT_BYTES_FOR(20, 16));
    expect(LEAF_SCRIPT_BYTES_FOR(20, 16)).toBe(1319 * 20 + 3);
    expect(thresholdLeafScript(17, keys).length).toBe(1319 * 20 + 4);
    expect(thresholdLeafScript(20, keys).length).toBe(1319 * 20 + 4);
  });

  it('round-trips a 20-of-20 leaf, the largest btq-core will parse', () => {
    const keys = Array.from({ length: 20 }, (_, i) => fixtureKey(i));
    const parsed = parseThresholdLeaf(thresholdLeafScript(20, keys));
    expect(parsed!.m).toBe(20);
    expect(parsed!.pubkeys.length).toBe(20);
  });
});

describe('canonicalCosigners', () => {
  const keys = [fixtureKey(3), fixtureKey(1), fixtureKey(2)];

  it('sorts lexicographically', () => {
    const sorted = canonicalCosigners(keys).map(bytesToHex);
    expect(sorted).toEqual([...sorted].sort());
  });

  it('is order independent', () => {
    const a = canonicalCosigners(keys).map(bytesToHex);
    const b = canonicalCosigners([...keys].reverse()).map(bytesToHex);
    expect(a).toEqual(b);
  });

  it('copies, so a later mutation of the caller array cannot move an address', () => {
    const input = [fixtureKey(1)];
    const out = canonicalCosigners(input);
    input[0]![0] = (input[0]![0]! ^ 0xff) & 0xff;
    expect(out[0]![0]).not.toBe(input[0]![0]);
  });

  it('rejects a duplicate key: it would fill more than one signature slot', () => {
    expect(() => canonicalCosigners([fixtureKey(1), fixtureKey(2), fixtureKey(1)]))
      .toThrow(/duplicate cosigner/);
    try {
      canonicalCosigners([fixtureKey(1), fixtureKey(1)]);
      expect.unreachable('a duplicate cosigner key must be refused');
    } catch (e) {
      expect(e).toBeInstanceOf(WalletError);
      expect((e as WalletError).code).toBe('BAD_PARAMS');
    }
  });

  it('rejects an empty set and more than 20 cosigners', () => {
    expect(() => canonicalCosigners([])).toThrow(WalletError);
    expect(() => canonicalCosigners(Array.from({ length: 21 }, (_, i) => fixtureKey(i)))).toThrow(WalletError);
    expect(canonicalCosigners(Array.from({ length: 20 }, (_, i) => fixtureKey(i))).length).toBe(20);
  });

  it('rejects a wrong-length key and the degenerate encodings', () => {
    expect(() => canonicalCosigners([new Uint8Array(32)])).toThrow(/1312 bytes/);
    expect(() => canonicalCosigners([new Uint8Array(PUBLIC_KEY_BYTES)])).toThrow(/degenerate/);
    const zeroRho = fixtureKey(1);
    zeroRho.fill(0, 0, 32);
    expect(isFullyValidPublicKey(zeroRho)).toBe(false);
    const zeroT1 = fixtureKey(1);
    zeroT1.fill(0, 32);
    expect(isFullyValidPublicKey(zeroT1)).toBe(false);
    expect(isFullyValidPublicKey(fixtureKey(1))).toBe(true);
  });
});

describe('thresholdLeafScript rejects', () => {
  it('a threshold outside 1..n', () => {
    const keys = [fixtureKey(1), fixtureKey(2)];
    expect(() => thresholdLeafScript(0, keys)).toThrow(WalletError);
    expect(() => thresholdLeafScript(3, keys)).toThrow(WalletError);
    expect(() => thresholdLeafScript(1.5, keys)).toThrow(WalletError);
  });

  it('an empty or oversized cosigner set', () => {
    expect(() => thresholdLeafScript(1, [])).toThrow(WalletError);
    expect(() => thresholdLeafScript(1, Array.from({ length: 21 }, (_, i) => fixtureKey(i)))).toThrow(WalletError);
  });

  it('a wrong-length key', () => {
    expect(() => thresholdLeafScript(1, [new Uint8Array(1311)])).toThrow(/1312 bytes/);
  });
});

describe('parseThresholdLeaf', () => {
  const keys = [fixtureKey(1), fixtureKey(2), fixtureKey(3)];
  const leaf = thresholdLeafScript(2, keys);
  // OP_0, OP_TOALTSTACK, then the 3-byte OP_PUSHDATA2 header, then the key.
  const keyAt = 1 + 1 + 3;
  const checksigAt = keyAt + PUBLIC_KEY_BYTES;

  /** Splice a replacement over `[from, to)` of the leaf. */
  function splice(from: number, to: number, replacement: number[]): Uint8Array {
    const out = new Uint8Array(leaf.length - (to - from) + replacement.length);
    out.set(leaf.subarray(0, from), 0);
    out.set(replacement, from);
    out.set(leaf.subarray(to), from + replacement.length);
    return out;
  }

  it('rejects an empty script', () => {
    expect(parseThresholdLeaf(new Uint8Array(0))).toBeNull();
  });

  it('rejects a leaf that does not open with OP_0', () => {
    const bad = Uint8Array.from(leaf);
    bad[0] = 0x51; // OP_1
    expect(parseThresholdLeaf(bad)).toBeNull();
  });

  it('rejects trailing bytes after OP_GREATERTHANOREQUAL', () => {
    const bad = new Uint8Array(leaf.length + 1);
    bad.set(leaf);
    bad[leaf.length] = 0x75; // OP_DROP
    expect(parseThresholdLeaf(bad)).toBeNull();
  });

  it('rejects a truncated leaf', () => {
    expect(parseThresholdLeaf(leaf.subarray(0, leaf.length - 1))).toBeNull();
    expect(parseThresholdLeaf(leaf.subarray(0, 400))).toBeNull();
  });

  it('rejects a swapped opcode inside a cosigner block', () => {
    expect(leaf[checksigAt]).toBe(0xbb); // OP_CHECKSIGDILITHIUM
    for (const offset of [1, 2, checksigAt, checksigAt + 1, checksigAt + 2]) {
      const bad = Uint8Array.from(leaf);
      bad[offset] = 0x75; // OP_DROP
      expect(parseThresholdLeaf(bad)).toBeNull();
    }
  });

  it('rejects a degenerate public key', () => {
    // Zero only rho, leaving the push length intact, so this reaches
    // isFullyValidPublicKey rather than stopping at the size check above it.
    const zeroRho = Uint8Array.from(leaf);
    zeroRho.fill(0, keyAt, keyAt + 32);
    expect(parseThresholdLeaf(zeroRho)).toBeNull();
    const zeroT1 = Uint8Array.from(leaf);
    zeroT1.fill(0, keyAt + 32, checksigAt);
    expect(parseThresholdLeaf(zeroT1)).toBeNull();
  });

  it('rejects a key push whose declared length is not 1312', () => {
    const short = Uint8Array.from(leaf);
    short[3] = 0x1f; // 0x051f = 1311, still in bounds
    expect(parseThresholdLeaf(short)).toBeNull();
    const long = Uint8Array.from(leaf);
    long[3] = 0x21; // 0x0521 = 1313
    expect(parseThresholdLeaf(long)).toBeNull();
  });

  it('rejects a threshold of 0, above n, or negative', () => {
    const zero = Uint8Array.from(leaf);
    zero[zero.length - 2] = 0x00; // OP_0
    expect(parseThresholdLeaf(zero)).toBeNull();
    const tooBig = Uint8Array.from(leaf);
    tooBig[tooBig.length - 2] = 0x54; // OP_4, above n = 3
    expect(parseThresholdLeaf(tooBig)).toBeNull();
    const opNegate = Uint8Array.from(leaf);
    opNegate[opNegate.length - 2] = 0x4f; // OP_1NEGATE — not a push, no data
    expect(parseThresholdLeaf(opNegate)).toBeNull();
    // A pushed -2 (0x82 is -2 in CScriptNum's sign-bit encoding).
    expect(parseThresholdLeaf(splice(leaf.length - 2, leaf.length - 1, [0x01, 0x82]))).toBeNull();
  });

  it('rejects a threshold push longer than 4 bytes', () => {
    expect(parseThresholdLeaf(splice(leaf.length - 2, leaf.length - 1, [0x05, 2, 0, 0, 0, 0]))).toBeNull();
  });

  it('rejects a missing OP_GREATERTHANOREQUAL', () => {
    const bad = Uint8Array.from(leaf);
    bad[bad.length - 1] = 0xa3; // OP_GREATERTHAN
    expect(parseThresholdLeaf(bad)).toBeNull();
  });

  it('rejects more than 20 cosigners', () => {
    // btq-core stops at MAX_PUBKEYS_PER_MULTISIG (src/script/script.h:35), so a
    // 21-key leaf is not a threshold leaf to the node either.
    const twenty = thresholdLeafScript(20, Array.from({ length: 20 }, (_, i) => fixtureKey(i)));
    const blocks = 1 + 20 * LEAF_BYTES_PER_COSIGNER;   // OP_0 and 20 cosigner blocks
    const extra = thresholdLeafScript(1, [fixtureKey(99)]).subarray(1, 1 + LEAF_BYTES_PER_COSIGNER);
    const twentyOne = new Uint8Array(blocks + LEAF_BYTES_PER_COSIGNER + 2);
    twentyOne.set(twenty.subarray(0, blocks), 0);
    twentyOne.set(extra, blocks);                       // a 21st, distinct, cosigner
    twentyOne[twentyOne.length - 2] = 0x51;             // OP_1
    twentyOne[twentyOne.length - 1] = 0xa2;             // OP_GREATERTHANOREQUAL
    // Positive control: the identical splice stopping at 20 keys parses, so
    // the rejection below is about the count and not about the surgery.
    const control = new Uint8Array(blocks + 2);
    control.set(twenty.subarray(0, blocks), 0);
    control[blocks] = 0x51;
    control[blocks + 1] = 0xa2;
    expect(parseThresholdLeaf(control)!.pubkeys.length).toBe(20);

    expect(parseThresholdLeaf(twentyOne)).toBeNull();
  });

  it('accepts encodings btq-core accepts but would not itself emit', () => {
    // ParseThresholdAccumulator is built on CScript::GetOp and
    // DecodePushedNumber(fRequireMinimal=false) (src/script/dilithium_leaf.cpp:35),
    // neither of which requires a minimal push. A parser stricter than
    // consensus would fail to recognise coins the chain considers spendable.
    const key = fixtureKey(9);

    // <2> pushed as the non-minimal 3-byte CScriptNum 02 02 00.
    const nonMinimalM = splice(leaf.length - 2, leaf.length - 1, [0x02, 0x02, 0x00]);
    expect(parseThresholdLeaf(nonMinimalM)!.m).toBe(2);

    // The same key pushed with OP_PUSHDATA1 and with OP_PUSHDATA4 instead of
    // the OP_PUSHDATA2 btq-core's builder picks.
    for (const header of [[0x4c, 0x20], [0x4e, 0x20, 0x05, 0x00, 0x00]]) {
      const script = new Uint8Array([
        0x00, 0x6b, ...header, ...key, 0xbb, 0x6c, 0x93, 0x51, 0xa2,
      ]);
      // OP_PUSHDATA1 cannot express 1312, so only the PUSHDATA4 form is a
      // valid 1-of-1; the PUSHDATA1 form must be rejected on size.
      const parsed = parseThresholdLeaf(script);
      if (header[0] === 0x4e) {
        expect(parsed!.m).toBe(1);
        expect(bytesToHex(parsed!.pubkeys[0]!)).toBe(bytesToHex(key));
      } else {
        expect(parsed).toBeNull();
      }
    }
  });

  it('rejects a single-key leaf, which is a different template', () => {
    expect(parseThresholdLeaf(singleKeyLeafScript(fixtureKey(1)))).toBeNull();
  });
});
